version: "3.8"

services:
    test:
        container_name: test-app
        build:
            context: .
            dockerfile: Dockerfile
            args:
                DIAGRAM_NAME: kubernetes
        stdin_open: true # docker run -i
        tty: true # docker run -t
        environment:
            GOARCH: "amd64"
            GOBIN: ""
            GOEXE: ""
            GOHOSTARCH: "amd64"
            GOHOSTOS: "linux"
            GOOS: "linux"
            GOPATH: "/go"
            GORACE: ""
            GOROOT: "/usr/local/go"
            GOTOOLDIR: "/usr/local/go/pkg/tool/linux_amd64"
            GO15VENDOREXPERIMENT: "1"
            CC: "gcc"
            GOGCCFLAGS: "-fPIC -m64 -pthread -fmessage-length=0"
            CXX: "g++"
            CGO_ENABLED: "1"
        volumes:
          - .:/go/src/app
          - ./diagrams:/home/diagrams

